import React from 'react';
import { useNavigate } from 'react-router-dom';
import './LandingPage.css';

const LandingPage = () => {
  const navigate = useNavigate();

  return (
    <div className="landing-page">
      {/* Navigation */}
      <nav className="navbar">
        <div className="nav-container">
          <div className="nav-logo">
            <div className="logo-icon">⚡</div>
            <span className="logo-text">QuestLearn</span>
          </div>
          <div className="nav-buttons">
            <button 
              className="nav-btn signin-btn"
              onClick={() => navigate('/login')}
            >
              Sign In
            </button>
            <button 
              className="nav-btn getstarted-btn"
              onClick={() => navigate('/signup')}
            >
              Get Started
            </button>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="hero-section">
        <div className="hero-container">
          <div className="hero-badge">
            <span className="badge-icon">✨</span>
            <span>AI-Powered Learning Platform</span>
          </div>
          
          <h1 className="hero-title">
            Master Coding with
            <br />
            <span className="gradient-text">AI-Powered Quests</span>
          </h1>
          
          <p className="hero-description">
            Transform your programming journey with personalized AI-generated
            challenges, interactive coding exercises, and gamified learning
            experiences.
          </p>
          
          <div className="hero-buttons">
            <button 
              className="cta-button primary"
              onClick={() => navigate('/signup')}
            >
              <span className="button-icon">🚀</span>
              Start Learning Free
              <span className="arrow">→</span>
            </button>
            <button 
              className="cta-button secondary"
              onClick={() => navigate('/login')}
            >
              Sign In to Continue
            </button>
          </div>
        </div>
      </section>

      {/* Stats Section */}
      <section className="stats-section">
        <div className="stats-container">
          <div className="stat-item">
            <div className="stat-icon">👥</div>
            <div className="stat-number">10K+</div>
            <div className="stat-label">Active Learners</div>
          </div>
          <div className="stat-item">
            <div className="stat-icon">💻</div>
            <div className="stat-number">500+</div>
            <div className="stat-label">Coding Challenges</div>
          </div>
          <div className="stat-item">
            <div className="stat-icon">📚</div>
            <div className="stat-number">50+</div>
            <div className="stat-label">Topics Covered</div>
          </div>
          <div className="stat-item">
            <div className="stat-icon">📈</div>
            <div className="stat-number">95%</div>
            <div className="stat-label">Success Rate</div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="features-section">
        <div className="features-container">
          <h2 className="section-title">Why Choose QuestLearn?</h2>
          <p className="section-subtitle">
            Experience the future of coding education with our innovative features
          </p>
          
          <div className="features-grid">
            <div className="feature-card">
              <div className="feature-icon ai-icon">🧠</div>
              <h3 className="feature-title">AI-Powered Learning</h3>
              <p className="feature-description">
                Get personalized quests generated by advanced AI
                based on your skill level and learning pace.
              </p>
            </div>
            
            <div className="feature-card">
              <div className="feature-icon coding-icon">💻</div>
              <h3 className="feature-title">Interactive Coding</h3>
              <p className="feature-description">
                Practice with real coding challenges and get instant
                feedback on your solutions.
              </p>
            </div>
            
            <div className="feature-card">
              <div className="feature-icon gamified-icon">🏆</div>
              <h3 className="feature-title">Gamified Experience</h3>
              <p className="feature-description">
                Earn XP, level up, unlock achievements, and
                compete with other learners on the leaderboard.
              </p>
            </div>
            
            <div className="feature-card">
              <div className="feature-icon help-icon">🎯</div>
              <h3 className="feature-title">Smart AI Help</h3>
              <p className="feature-description">
                Get hints, concept explanations, and code
                optimizations powered by AI when you're stuck.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Learning Paths Section */}
      <section className="paths-section">
        <div className="paths-container">
          <h2 className="section-title">Choose Your Learning Path</h2>
          
          <div className="paths-grid">
            <div className="path-card popular">
              <div className="popular-badge">⭐ Popular</div>
              <div className="path-icon js-icon">📦</div>
              <h3 className="path-title">JavaScript</h3>
              <div className="path-meta">
                <span className="quest-count">25 Quests</span>
                <span className="difficulty beginner">Beginner</span>
              </div>
              <button className="path-button">Start Learning</button>
            </div>
            
            <div className="path-card popular">
              <div className="popular-badge">⭐ Popular</div>
              <div className="path-icon python-icon">🐍</div>
              <h3 className="path-title">Python</h3>
              <div className="path-meta">
                <span className="quest-count">28 Quests</span>
                <span className="difficulty beginner">Beginner</span>
              </div>
              <button className="path-button">Start Learning</button>
            </div>
            
            <div className="path-card">
              <div className="path-icon react-icon">⚛️</div>
              <h3 className="path-title">React</h3>
              <div className="path-meta">
                <span className="quest-count">35 Quests</span>
                <span className="difficulty advanced">Advanced</span>
              </div>
              <button className="path-button">Start Learning</button>
            </div>
            
            <div className="path-card">
              <div className="path-icon cpp-icon">🔵</div>
              <h3 className="path-title">C++</h3>
              <div className="path-meta">
                <span className="quest-count">30 Quests</span>
                <span className="difficulty intermediate">Intermediate</span>
              </div>
              <button className="path-button">Start Learning</button>
            </div>
            
            <div className="path-card">
              <div className="path-icon html-icon">🌐</div>
              <h3 className="path-title">HTML/CSS</h3>
              <div className="path-meta">
                <span className="quest-count">24 Quests</span>
                <span className="difficulty beginner">Beginner</span>
              </div>
              <button className="path-button">Start Learning</button>
            </div>
            
            <div className="path-card">
              <div className="path-icon node-icon">🟢</div>
              <h3 className="path-title">Node.js</h3>
              <div className="path-meta">
                <span className="quest-count">22 Quests</span>
                <span className="difficulty intermediate">Intermediate</span>
              </div>
              <button className="path-button">Start Learning</button>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="cta-section">
        <div className="cta-container">
          <h2 className="cta-title">Ready to Start Your Coding Journey?</h2>
          <p className="cta-description">
            Join thousands of learners who are mastering programming with AI-
            powered quests. Start your free journey today!
          </p>
          
          <div className="cta-buttons">
            <button 
              className="cta-button primary large"
              onClick={() => navigate('/signup')}
            >
              <span className="button-icon">⚡</span>
              Create Free Account
              <span className="arrow">→</span>
            </button>
            <button 
              className="cta-button secondary large"
              onClick={() => navigate('/login')}
            >
              Sign In Now
            </button>
          </div>
          
          <div className="cta-features">
            <div className="cta-feature">
              <span className="check-icon">✓</span>
              <span>Free to start</span>
            </div>
            <div className="cta-feature">
              <span className="check-icon">✓</span>
              <span>No credit card required</span>
            </div>
            <div className="cta-feature">
              <span className="check-icon">✓</span>
              <span>Cancel anytime</span>
            </div>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="footer">
        <div className="footer-container">
          <div className="footer-content">
            <div className="footer-brand">
              <div className="footer-logo">
                <div className="logo-icon">⚡</div>
                <span className="logo-text">QuestLearn</span>
              </div>
              <p className="footer-description">
                Empowering developers worldwide with AI-powered learning experiences.
              </p>
            </div>
            
            <div className="footer-links">
              <div className="footer-column">
                <h4>Learning Paths</h4>
                <ul>
                  <li><a href="#javascript">JavaScript</a></li>
                  <li><a href="#python">Python</a></li>
                  <li><a href="#react">React</a></li>
                  <li><a href="#cpp">C++</a></li>
                </ul>
              </div>
              
              <div className="footer-column">
                <h4>Features</h4>
                <ul>
                  <li><a href="#ai-quests">AI-Generated Quests</a></li>
                  <li><a href="#interactive">Interactive Coding</a></li>
                  <li><a href="#progress">Progress Tracking</a></li>
                  <li><a href="#leaderboards">Leaderboards</a></li>
                </ul>
              </div>
              
              <div className="footer-column">
                <h4>Support</h4>
                <ul>
                  <li><a href="#help">Help Center</a></li>
                  <li><a href="#community">Community</a></li>
                  <li><a href="#contact">Contact Us</a></li>
                  <li><a href="#privacy">Privacy Policy</a></li>
                </ul>
              </div>
            </div>
          </div>
          
          <div className="footer-bottom">
            <p>© 2024 QuestLearn. All rights reserved. Built with ❤️ for developers.</p>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default LandingPage;
